const Controller = require('./controller')
const router = require('express').Router()
const authentification = require('../../middleware/authentification')

router.post('/new_claim',authentification, Controller.new_claim)
router.post('/update_patient',authentification, Controller.update_patient)
router.post('/delete_patient',authentification, Controller.delete_patient)
router.post('/set_claim_data',authentification, Controller.set_claim_data)
router.post('/idrg_diagnosa_set',authentification, Controller.idrg_diagnosa_set)
router.post('/idrg_diagnosa_get',authentification, Controller.idrg_diagnosa_get)
router.post('/idrg_prosedur_set',authentification, Controller.idrg_prosedur_set)
router.post('/idrg_prosedur_get',authentification, Controller.idrg_prosedur_get)
router.post('/grouper_idrg_stage_1',authentification, Controller.grouper_idrg_stage_1)
router.post('/idrg_grouper_final',authentification, Controller.idrg_grouper_final)
router.post('/idrg_grouper_reedit',authentification, Controller.idrg_grouper_reedit)
router.post('/idrg_to_inacbg_import',authentification, Controller.idrg_to_inacbg_import)
router.post('/inacbg_diagnosa_set',authentification, Controller.inacbg_diagnosa_set)
router.post('/inacbg_prosedur_set',authentification, Controller.inacbg_prosedur_set)
router.post('/grouper_inacbg_stage_1',authentification, Controller.grouper_inacbg_stage_1)
router.post('/grouper_inacbg_stage_2',authentification, Controller.grouper_inacbg_stage_2)
router.post('/inacbg_grouper_final',authentification, Controller.inacbg_grouper_final)
router.post('/inacbg_grouper_reedit',authentification, Controller.inacbg_grouper_reedit)
router.post('/claim_final',authentification, Controller.claim_final)
router.post('/reedit_claim',authentification, Controller.reedit_claim)
router.post('/send_claim',authentification, Controller.send_claim)
router.post('/send_claim_individual',authentification, Controller.send_claim_individual)
router.post('/get_claim_data',authentification, Controller.get_claim_data)
router.post('/get_claim_status',authentification, Controller.get_claim_status)
router.post('/delete_claim',authentification, Controller.delete_claim)
router.post('/claim_print',authentification, Controller.claim_print)
router.post('/search_diagnosis_inagrouper',authentification, Controller.search_diagnosis_inagrouper)
router.post('/search_procedures_inagrouper',authentification, Controller.search_procedures_inagrouper)
router.post('/search_diagnosis',authentification, Controller.search_diagnosis)
router.post('/search_procedures',authentification, Controller.search_procedures)
router.post('/generate_claim_number',authentification, Controller.generate_claim_number)
router.post('/sitb_validate',authentification, Controller.sitb_validate)
router.post('/sitb_invalidate',authentification, Controller.sitb_invalidate)

// Workflow Management Endpoints
router.post('/workflow/history',authentification, Controller.get_workflow_history)
router.post('/workflow/status',authentification, Controller.get_workflow_status)
router.post('/workflow/reset',authentification, Controller.reset_workflow)

module.exports = router